version: '3.4'

services:

  grpcservice:
    image: ${DOCKER_REGISTRY-}grpcservice
    container_name: grpcservice
    build:
      context: .
      dockerfile: src/GrpcService/Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: webapi
    depends_on: 
      - grpcservice
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile   
      
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: jaeger
    depends_on: 
      - grpcservice
      - webapi
  
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
    container_name: aspire
    depends_on: 
      - grpcservice
      - webapi

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    depends_on: 
      - grpcservice
      - webapi

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    depends_on:
      - prometheus
      - jaeger