version: '3.4'

services:

  grpcservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "3100:8080"
      - "3131:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - GrpcSettings__GreeterUrl=https://grpcservice:8081
    ports:
      - "4000:8080"
      - "4040:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  jaeger:
    ports:
        # https://www.jaegertracing.io/docs/1.62/getting-started/
        - "16686:16686" # Jaeger UI
        # - "4317:4317" # accept OpenTelemetry Protocol (OTLP) over gRPC (commented for avoid collector port clash)
        - "4318:4318" # accept OpenTelemetry Protocol (OTLP) over HTTP

  aspire:
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888" # Aspire Dashboard
      - "4319:18889" # accept OpenTelemetry Protocol (OTLP) over gRPC

  prometheus:
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
     - '3000:3000'
    volumes:
     - ./grafana.datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  opentelemetry-collector:
    environment:
     - JAEGER_ENDPOINT=jaeger:4317
    ports:
    # https://opentelemetry.io/docs/collector/installation/
     - 8889:8889 # Prometheus exporter metrics
     - 13133:13133 # health_check extension
     - 55679:55679 # zpages extension
     - 4317:4317 # OTLP gRPC receiver
    command: --config /etc/otelcol-contrib/config.yaml
    volumes:
     - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml