version: '3.4'

services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.62.0