receivers:
  otlp/collector:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # opentelemetry-collector GRPC port
      http:
        endpoint: 0.0.0.0:4318 # opentelemetry-collector HTTP port

processors:
  batch:

exporters:
  debug:
  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT}"  # Jaeger exporter
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"        # Prometheus exporter
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"   # Loki exporter
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp/collector]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp/collector]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp/collector]
      processors: [batch]
      exporters: [debug, loki]
